# Generated by Django 4.2.1 on 2023-05-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('age_in_months', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='staticfiles/')),
                ('city', models.CharField(max_length=255)),
                ('needs_an_urgent_adoption', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-needs_an_urgent_adoption'],
            },
        ),
    ]
