# Generated by Django 4.2.1 on 2023-05-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopter', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopter', to='adopter.adopter')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requested_pet', to='pet.pet')),
            ],
            options={
                'ordering': ['approved'],
                'unique_together': {('pet', 'adopter')},
            },
        ),
    ]
