# Generated by Django 4.2.1 on 2023-05-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0004_remove_adopter_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
